default:
  input_path : data/eval_dataset.csv
  output_path: result/eval_result.csv
  dataset_id : bigquery-public-data.crypto_ethereum

  embedder:
    provider: gemini
    params:
      model : gemini-embedding-001

  vectorstore:
    provider: opensearch
    params:
      opensearch_url : http://localhost:9200
      index_name : bird_train_examples
      engine: faiss
      use_ssl : true
      verify_certs: false
      ssl_show_warn: false
      timeout : 120

  llm:
    factual:
      provider: openai
      params:
        model: gpt-4.1-mini
        temperature : 0.0
        top_p : 0.0
    creative:
      provider: openai
      params:
        model: gpt-4.1-mini
        temperature : 0.9
        top_p : 0.9
    


  self_consistency:
    divide_and_conquer : 2
    query_planning: 2
    roleplay : 2

  max_revision_count : 5

  




    
